<a href="https://colab.research.google.com/github/RLungWu/Dive-into-DL/blob/main/Chapter/DDL_3.3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Dive into DL 3.3 簡潔實現Linear Regression

In [1]:
from datetime import datetime
import pytz

taiwan = pytz.timezone('Asia/Taipei')

now = datetime.now(taiwan)

print(f"Start at: {now}")


Start at: 2024-03-27 15:42:39.016504+08:00


In [2]:
! pip install d2l

In [6]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [7]:
def load_array(data_arrays, batch_size, is_train = True):
    #Build a PyToch iterator
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [8]:
next(iter(data_iter))

[tensor([[-1.6756,  0.4719],
         [ 1.1988,  1.0616],
         [ 0.0132, -1.1724],
         [ 0.1307,  3.0656],
         [-0.0261,  0.3798],
         [-0.4231,  0.5900],
         [ 0.3869,  0.0581],
         [-1.6162,  0.3271],
         [ 0.6905,  0.1119],
         [-1.3080,  0.7182]]),
 tensor([[-0.7392],
         [ 2.9942],
         [ 8.2246],
         [-5.9584],
         [ 2.8558],
         [ 1.3400],
         [ 4.7902],
         [-0.1492],
         [ 5.1900],
         [-0.8515]])]

### 定義模型

In [9]:
from torch import nn

net = nn.Sequential(nn.Linear(2,1))

### 初始化模型

In [10]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

### 損失函數

In [11]:
loss = nn.MSELoss()

### 定義優化算法

In [12]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

### Train

In [14]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f"epoch {epoch + 1}, loss {l:f}")

epoch 1, loss 0.000106
epoch 2, loss 0.000107
epoch 3, loss 0.000108


In [15]:
w = net[0].weight.data
print(f"w: {w}")
print(f"Estimated loss: ", true_w - w.reshape(true_w.shape))

b = net[0].bias.data
print(b)
print('Estimate of b: ', true_b - b)

w: tensor([[ 1.9989, -3.4005]])
Estimated loss:  tensor([0.0011, 0.0005])
tensor([4.2010])
Estimate of b:  tensor([-0.0010])
